@startuml

!theme plain
top to bottom direction
skinparam linetype ortho
skinparam classAttributeIconSize 0

class Block {
  - grosseStrasse: Integer
  - nurZweier: Integer
  - nurSechser: Integer
  - viererPasch: Integer
  - nurEinsen: Integer
  - kniffel: Integer
  - nurFunfer: Integer
  - nurVierer: Integer
  - kleineStrasse: Integer
  - fullHouse: Integer
  - bonus: Integer
  - chance: Integer
  - dreierPasch: Integer
  - nurDreier: Integer
}
class Kniffel {
  - wuerfel: List<Integer>
  - id: Long
  - aktiverSpielerIndex: int
  - teilnehmer: List<Spieler>
  - uebrigeWuerfe: int
  - runde: int
}
class KniffelController {
  - kniffelService: KniffelService
  + getNeuesSpiel(ArrayList<Spieler>): Kniffel
}
class KniffelService {
  - spielliste: ArrayList<Kniffel>
  + spielStarten(ArrayList<Spieler>): Kniffel
}
class Spieler {
  - name: String
  - siege: int
  - block: Block
  - punktestand: int
}

Kniffel                   "1 " *-[#595959,plain]-> "*" Spieler
KniffelController         "1 " *-[#595959,plain]-> "1 " KniffelService
KniffelService             -[#595959,dashed]->  Kniffel
KniffelService            "1  " *-[#595959,plain]-> " * " Kniffel
Spieler                   "1 " *-[#595959,plain]-> "1 " Block
@enduml
